[package]
edition = "2021"
name = "sleigh-rs"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/rbran/sleigh-rs"
license = "MIT"
description = "Ghidra Sleigh parser"

[profile.release]
debug = true

[dependencies]
nom = "7"
thiserror = "1"
indexmap = "1.9"
sleigh4rust = "0.1"
