[package]
edition = "2021"
name = "sleigh-rs"
version = "0.1.5"
readme = "README.md"
repository = "https://github.com/rbran/sleigh-rs"
license = "MIT"
description = "Ghidra Sleigh parser"

[dependencies]
nom = "7"
thiserror = "1"
tracing = "0.1.40"
